comments: comments.md
template_dir: templates

year: 2027

Vacances scolaires:
  css_class: "vacancesscolaires"
  dates:
    - 19/12/2026 - 03/01/2027
    - 06/02 - 21/02        # hiver
    - 03/04 - 18/04        # printemps
    - 03/07 - 31/08        # été
    # - 17/10 - 01/11        # toussaint
    # - 17/10/27 - 01/11/28  # noel

# Les jours fériés sont calculés automatiquement.
