comments: comments.md
template_dir: templates

year: 2026

Vacances scolaires:
  css_class: "vacancesscolaires"
  dates:
    - 20/12/2025 - 04/01/2026
    - 21/02 - 08/03
    - 18/04 - 03/05
    - 04/07 - 31/08
    - 17/10 - 01/11
    - 19/12 - 03/01/2027


# Les jours fériés sont calculés automatiquement.
